# Generated by Django 5.2.13 on 2026-04-27 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='имя игрока')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profile', to=settings.AUTH_USER_MODEL, verbose_name='аккаунт')),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'игроки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='день недели')),
                ('start_time_minutes', models.PositiveSmallIntegerField(verbose_name='начало')),
                ('end_time_minutes', models.PositiveSmallIntegerField(verbose_name='конец')),
                ('note', models.CharField(blank=True, max_length=160, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduler.player', verbose_name='игрок')),
            ],
            options={
                'verbose_name': 'слот расписания',
                'verbose_name_plural': 'слоты расписания',
                'ordering': ['player_id', 'day_of_week', 'start_time_minutes'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time_minutes__gte', 0), ('start_time_minutes__lte', 1380)), name='slot_start_between_0000_and_2300'), models.CheckConstraint(condition=models.Q(('end_time_minutes__gte', 60), ('end_time_minutes__lte', 1440)), name='slot_end_between_0100_and_2400'), models.CheckConstraint(condition=models.Q(('end_time_minutes__gt', models.F('start_time_minutes'))), name='slot_end_after_start')],
            },
        ),
    ]
