# Generated by Django 5.2.13 on 2026-04-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_seed_players'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='slot_start_between_0000_and_2300',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='slot_end_between_0100_and_2400',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='slot_end_after_start',
        ),
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatars/', verbose_name='аватар'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='slot_type',
            field=models.CharField(choices=[('available', 'Диапазон времени'), ('unavailable', 'Не могу в этот день')], default='available', max_length=16, verbose_name='тип записи'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='end_time_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='конец'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='start_time_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='начало'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time_minutes__gt', models.F('start_time_minutes')), ('end_time_minutes__gte', 60), ('end_time_minutes__lte', 1440), ('slot_type', 'available'), ('start_time_minutes__gte', 0), ('start_time_minutes__lte', 1380)), models.Q(('end_time_minutes__isnull', True), ('slot_type', 'unavailable'), ('start_time_minutes__isnull', True)), _connector='OR'), name='slot_valid_by_type'),
        ),
    ]
