# Generated by Django 5.2.13 on 2026-04-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_player_battle_tags_player_discord_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayeventtype',
            name='event_type',
            field=models.CharField(blank=True, choices=[('', 'Без события'), ('tournament', 'Tournament'), ('scrim', 'Scrim'), ('competitive', 'Competitive'), ('review', 'VOD Review')], default='', max_length=24, verbose_name='тип события'),
        ),
    ]
