# Generated by Django 5.2.13 on 2026-04-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_alter_dayeventtype_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar_link',
            field=models.URLField(blank=True, help_text='Для продакшена на Vercel используйте прямую ссылку на изображение.', verbose_name='ссылка на аватар'),
        ),
    ]
