# Generated by Django 5.2.13 on 2026-04-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_player_avatar_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar_content_type',
            field=models.CharField(blank=True, editable=False, max_length=80, verbose_name='mime тип аватара'),
        ),
        migrations.AddField(
            model_name='player',
            name='avatar_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='данные аватара'),
        ),
    ]
