# Generated by Django 5.2.13 on 2026-04-28 20:50

import django.core.validators
from django.db import migrations, models


def seed_player_sort_order(apps, schema_editor):
    Player = apps.get_model('scheduler', 'Player')
    for index, player in enumerate(Player.objects.order_by('id'), start=1):
        player.sort_order = index
        player.save(update_fields=['sort_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_player_avatar_content_type_player_avatar_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='имя')),
                ('role', models.CharField(max_length=80, verbose_name='роль')),
                ('role_color', models.CharField(default='#4b607f', max_length=7, validators=[django.core.validators.RegexValidator(message='Укажите цвет в формате #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='цвет роли')),
                ('discord_tag', models.CharField(blank=True, max_length=120, verbose_name='discord тег')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок в списке')),
            ],
            options={
                'verbose_name': 'организаторский состав',
                'verbose_name_plural': 'организаторский состав',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'игрок', 'verbose_name_plural': 'игроки'},
        ),
        migrations.AddField(
            model_name='player',
            name='role_color',
            field=models.CharField(default='#4b607f', max_length=7, validators=[django.core.validators.RegexValidator(message='Укажите цвет в формате #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='цвет роли'),
        ),
        migrations.AddField(
            model_name='player',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='порядок в таблице'),
        ),
        migrations.RunPython(seed_player_sort_order, migrations.RunPython.noop),
    ]
