# Generated by Django 5.2.13 on 2026-04-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_discordconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('published_at', models.DateField(verbose_name='дата публикации')),
                ('type_label', models.CharField(max_length=80, verbose_name='тип обновления')),
                ('source_url', models.URLField(max_length=500, verbose_name='источник')),
                ('summary', models.TextField(blank=True, verbose_name='краткое описание')),
                ('hero_image_url', models.URLField(blank=True, max_length=500, verbose_name='изображение героя')),
                ('content_json', models.JSONField(blank=True, default=list, verbose_name='контент патча')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='синхронизировано')),
            ],
            options={
                'verbose_name': 'обновление игры',
                'verbose_name_plural': 'обновления игры',
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
