# Generated by Django 5.2.13 on 2026-05-15 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0022_limit_scheduleslot_note_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('feedback', 'Feedback'), ('other', 'Other')], max_length=20, verbose_name='тип')),
                ('message', models.TextField(max_length=2000, verbose_name='сообщение')),
                ('page_url', models.URLField(blank=True, max_length=500, verbose_name='страница')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done'), ('rejected', 'Rejected')], default='new', max_length=20, verbose_name='статус')),
                ('admin_note', models.TextField(blank=True, verbose_name='заметка администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedback',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
