# Generated by Django 5.2.13 on 2026-05-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0023_feedbackentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackentry',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('in_progress', 'In progress'), ('done', 'Done'), ('rejected', 'Rejected')], default='accepted', max_length=20, verbose_name='статус'),
        ),
    ]
